# Generated by Django 5.2.4 on 2025-07-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_blogpost_photo_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='photo_alt',
            field=models.CharField(default='Blog photo image.', max_length=255),
        ),
    ]
