# Generated by Django 5.2.4 on 2025-07-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_projectitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectitem',
            name='repo_id',
            field=models.PositiveBigIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
