# Generated by Django 5.2.4 on 2025-07-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_projectitem_repo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitem',
            name='repo_id',
            field=models.PositiveBigIntegerField(default=0, unique=True),
        ),
    ]
