# Generated by Django 5.2.4 on 2025-07-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='date_posted',
            new_name='created_at',
        ),
    ]
