# Generated by Django 5.2.4 on 2025-07-03 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_contactitem_rename_date_posted_blogpost_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
